# Create file secrets.yaml (unversioned) and enter base64 encoded secrets
# then apply the secrets before the file-service
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  aws_id: #Base64 secrets here
  aws_key: #Base64 secrets here
  aws_bucket: #Base64 secrets here
  aws_region: #Base64 secrets here